1. Write a python program which searches all the product under a particular product from www.amazon.in. The
product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for
guitars.

In [104]:
import selenium
from selenium import webdriver
import pandas as pd1
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
from selenium.common.exceptions import NoSuchElementException

In [105]:
driver1=webdriver.Chrome()

In [106]:
driver1.get("https://www.amazon.in/")

In [107]:
search_product=driver1.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
search_product.send_keys(input("Enter Product"))

Enter ProductKnife for Kitchen

In [108]:
search_icon=driver1.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
search_icon.click()

2. In the above question, now scrape the following details of each product listed in first 3 pages of your search
results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then
scrape all the products available under that product name. Details to be scraped are: "Brand
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [60]:
p_url=[]
for pages in range(3):
    print("scraped page",pages+1)
    product_url=driver1.find_elements(By.XPATH,'//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-4"]/a')
    for a in product_url:
        p_url.append(a.get_attribute('href'))
    next_button=driver1.find_element(By.XPATH,'//div[@class="a-section a-text-center s-pagination-container"]/span/a[3]')
    #next_button.click()
    time.sleep(3)
len(p_url)

scraped page 1
scraped page 2
scraped page 3

195

In [79]:
p_brand=[]
for b in p_url:
    driver1.get(b)
    time.sleep(10)
    try:
        product_brand=driver1.find_element(By.XPATH,'//div[@class="a-section a-spacing-small a-spacing-top-small"]/table/tbody/tr[2]/td[2]/span')
        p_brand.append(product_brand.text)
    except NoSuchElementException:
        p_brand.append('Not Present')
#next_button=driver4.find_element(By.XPATH,'//div[@class="a-section a-text-center s-pagination-container"]/span/a[3]')
#next_button.click()
#time.sleep(3)
print(p_brand)        
len(p_brand)

['Victorinox', 'Victorinox', 'Kai', 'Victorinox', 'CAROTE', 'Pigeon', 'Crystal', 'TOUARETAILS', 'Kai', 'Kai', 'Kai', 'NAALSA', 'AGARO', 'AGARO', 'AGARO', 'Pigeon', 'Glare', 'THE SR BRAND', 'voltonix', 'JINI COLLECTION', 'LEAWALL', 'GANESH', 'Pigeon', 'amazon basics', 'Godrej Cartini', 'Kai', 'Victorinox', 'Kai', 'Victorinox', 'BLACK', 'GANESH', 'Kai', 'Crystal', 'Godrej Cartini', 'IndiaCart', 'Victorinox', 'Glare', 'NAALSA', 'Pigeon', 'Victorinox', 'Kai', 'Ritu', 'Hotmark', 'rena germany', '30.1L x 13.1W x 10.6H Centimeters', 'HEXONIQ', 'ONICORN', 'Glare', 'Pigeon', 'Mockery', 'Kai', 'Crystal', 'Amazon Brand - Solimo', 'Crystal', 'GANESH', 'ALLWIN', 'Victorinox', 'Not Present', 'Silver', 'Victorinox', 'Kai', 'TOUARETAILS', 'Victorinox', 'AGARO', 'Kai', 'Victorinox', 'Victorinox', 'Kai', 'Victorinox', 'CAROTE', 'Pigeon', 'Crystal', 'TOUARETAILS', 'Kai', 'Kai', 'Kai', 'NAALSA', 'AGARO', 'AGARO', 'AGARO', 'Pigeon', 'Glare', 'THE SR BRAND', 'voltonix', 'JINI COLLECTION', 'LEAWALL', 'GANESH', 'Pigeon', 'amazon basics', 'Godrej Cartini', 'Kai', 'Victorinox', 'Kai', 'Victorinox', 'BLACK', 'GANESH', 'Kai', 'Crystal', 'Godrej Cartini', 'IndiaCart', 'Victorinox', 'Glare', 'NAALSA', 'Pigeon', 'Victorinox', 'Kai', 'Ritu', 'Hotmark', 'rena germany', '30.1L x 13.1W x 10.6H Centimeters', 'HEXONIQ', 'ONICORN', 'Glare', 'Pigeon', 'Mockery', 'Kai', 'Crystal', 'Amazon Brand - Solimo', 'Crystal', 'GANESH', 'ALLWIN', 'Victorinox', 'Not Present', 'Silver', 'Victorinox', 'Kai', 'TOUARETAILS', 'Victorinox', 'AGARO', 'Kai', 'Victorinox', 'Victorinox', 'Kai', 'Victorinox', 'CAROTE', 'Pigeon', 'Crystal', 'TOUARETAILS', 'Kai', 'Kai', 'Kai', 'NAALSA', 'AGARO', 'AGARO', 'AGARO', 'Pigeon', 'Glare', 'THE SR BRAND', 'voltonix', 'JINI COLLECTION', 'LEAWALL', 'GANESH', 'Pigeon', 'amazon basics', 'Godrej Cartini', 'Kai', 'Victorinox', 'Kai', 'Victorinox', 'BLACK', 'GANESH', 'Kai', 'Crystal', 'Godrej Cartini', 'IndiaCart', 'Victorinox', 'Glare', 'NAALSA', 'Pigeon', 'Victorinox', 'Kai', 'Ritu', 'Hotmark', 'rena germany', '30.1L x 13.1W x 10.6H Centimeters', 'HEXONIQ', 'ONICORN', 'Glare', 'Pigeon', 'Mockery', 'Kai', 'Crystal', 'Amazon Brand - Solimo', 'Crystal', 'GANESH', 'ALLWIN', 'Victorinox', 'Not Present', 'Silver', 'Victorinox', 'Kai', 'TOUARETAILS', 'Victorinox', 'AGARO', 'Kai']

195

In [90]:
p_price=[]
for c in p_url:
    driver1.get(c)
    time.sleep(5)
    try:
        product_price=driver1.find_element(By.XPATH,'//div[@class="a-section a-spacing-none aok-align-center aok-relative"]/span[3]/span[2]/span[2]')
        p_price.append(product_price.text)
    except NoSuchElementException:
        p_price.append('Not Present')
#next_button=driver4.find_element(By.XPATH,'//div[@class="a-section a-text-center s-pagination-container"]/span/a[3]')
#next_button.click()
#time.sleep(3)
print(p_price)        
len(p_price)

['483', '401', '419', '483', '251', '389', 'Not Present', '1,699', '1,349', '419', '349', '298', '299', '699', '899', '209', 'Not Present', '100', '698', '689', '129', '199', '229', '1,425', '450', '399', '401', '349', '401', '299', '77', '519', 'Not Present', '450', 'Not Present', '483', 'Not Present', 'Not Present', '529', '483', '419', 'Not Present', '100', '267', '362', '521', '289', 'Not Present', '200', '657', '419', 'Not Present', '526', '163', '77', '330', '483', '251', '899', '1,287', '1,349', '1,699', '1,177', '899', '1,349', '483', '401', '419', '483', '251', '389', 'Not Present', '1,699', '1,349', '419', '349', '298', '299', '699', '899', '209', 'Not Present', '100', '698', '689', '129', '199', '229', '1,425', '450', '399', '401', '349', '401', '299', '77', '519', 'Not Present', '450', 'Not Present', '483', 'Not Present', 'Not Present', '529', '483', '419', 'Not Present', '100', '267', '362', '521', '289', 'Not Present', '200', '657', '419', 'Not Present', '526', '163', '77', '330', '483', '251', '899', '1,287', '1,349', '1,699', '1,177', '899', '1,349', '483', '401', '419', '483', '251', '389', 'Not Present', '1,699', '1,349', '419', '349', '298', '299', '699', '899', '209', 'Not Present', '100', '698', '689', '129', '199', '229', '1,425', '450', '399', '401', '349', '401', '299', '77', '519', 'Not Present', '450', 'Not Present', '483', 'Not Present', 'Not Present', '529', '483', '419', 'Not Present', '100', '267', '362', '521', '289', 'Not Present', '200', '657', '419', 'Not Present', '526', '163', '77', '330', '483', '251', '899', '1,287', '1,349', '1,699', '1,177', '899', '1,349']

195

In [96]:
p_return=[]
for d in p_url:
    driver1.get(d)
    time.sleep(5)
    try:
        product_return=driver1.find_element(By.XPATH,'//div[@class="a-row icon-farm-wrapper"]/div[2]/span/div[2]/span')
        p_return.append(product_return.text)
    except NoSuchElementException:
        p_return.append('Not Present')
#next_button=driver4.find_element(By.XPATH,'//div[@class="a-section a-text-center s-pagination-container"]/span/a[3]')
#next_button.click()
#time.sleep(3)
print(p_return)        
len(p_return)

['10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '7 days Replacement', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Non-Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '7 days Replacement', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Non-Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '7 days Replacement', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Non-Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', 'Not Present', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable', '10 days Returnable']

195

In [103]:
p_delivery=[]
for e in p_url:
    driver1.get(e)
    time.sleep(5)
    try:
        product_delivery=driver1.find_element(By.XPATH,'//div[@class="a-box-group"]/div/div/div/div[4]/div/div[3]/div[10]/div/div/div/div/span/span[1]')
        p_delivery.append(product_delivery.text)
    except NoSuchElementException:
        p_delivery.append('Not Present')
#next_button=driver4.find_element(By.XPATH,'//div[@class="a-section a-text-center s-pagination-container"]/span/a[3]')
#next_button.click()
#time.sleep(3)
print(p_delivery)        
len(p_delivery)

['Sunday, 18 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Monday, 19 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Monday, 26 February', 'Saturday, 17 February', '12 - 20 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Monday, 19 February', 'Saturday, 17 February', '12 - 20 February', 'Saturday, 17 February', '14 - 21 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Monday, 26 February', 'Sunday, 18 February', 'Monday, 26 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Sunday, 18 February', 'Monday, 19 February', 'Not Present', 'Sunday, 18 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Monday, 19 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Monday, 26 February', 'Saturday, 17 February', '12 - 19 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Monday, 19 February', 'Saturday, 17 February', '12 - 20 February', 'Saturday, 17 February', '14 - 21 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Monday, 26 February', 'Sunday, 18 February', 'Monday, 26 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Sunday, 18 February', 'Monday, 19 February', 'Not Present', 'Sunday, 18 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Monday, 19 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Monday, 26 February', 'Saturday, 17 February', '14 - 19 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Monday, 19 February', 'Saturday, 17 February', '12 - 20 February', 'Saturday, 17 February', '14 - 21 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Monday, 26 February', 'Sunday, 18 February', 'Monday, 26 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Sunday, 18 February', 'Monday, 19 February', 'Not Present', 'Sunday, 18 February', 'Saturday, 17 February', 'Sunday, 18 February', 'Saturday, 17 February', 'Saturday, 17 February', 'Saturday, 17 February']

195

In [109]:
p_availability=[]
for f in p_url:
    driver1.get(f)
    time.sleep(5)
    try:
        product_availability=driver1.find_element(By.XPATH,'//div[@class="a-section a-spacing-none a-spacing-top-micro }"]/span')
        p_availability.append(product_availability.text)
    except NoSuchElementException:
        p_availability.append('Not Present')
#next_button=driver4.find_element(By.XPATH,'//div[@class="a-section a-text-center s-pagination-container"]/span/a[3]')
#next_button.click()
#time.sleep(3)
print(p_availability)        
len(p_availability)

['In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'Only 2 left in stock.', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', '', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', '', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'Only 2 left in stock.', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', '', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', '', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'Only 2 left in stock.', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', '', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', '', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock']

195

In [110]:
df2=pd1.DataFrame({"Product Brand":p_brand,"Price":p_price,"Return":p_return,"Delivery":p_delivery,"Availability":p_availability,"URL":p_url})
df2

,Product Brand,Price,Return,Delivery,Availability,URL
0,Victorinox,483,10 days Returnable,"Sunday, 18 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,Victorinox,401,10 days Returnable,"Sunday, 18 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Kai,419,Not Present,"Saturday, 17 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Victorinox,483,10 days Returnable,"Monday, 19 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,CAROTE,251,10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/Stainless-Knife-Kitchen-...
...,...,...,...,...,...,...
190,Kai,"1,349",10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/Kai-Premium-Stainless-Se...
191,TOUARETAILS,"1,699",10 days Returnable,"Sunday, 18 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
192,Victorinox,"1,177",10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
193,AGARO,899,10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
194,Kai,"1,349",10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [111]:
df2.to_csv('Amazon Product Data',index=False)

In [112]:
df2=pd1.read_csv('Amazon Product Data')
df2

,Product Brand,Price,Return,Delivery,Availability,URL
0,Victorinox,483,10 days Returnable,"Sunday, 18 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,Victorinox,401,10 days Returnable,"Sunday, 18 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Kai,419,Not Present,"Saturday, 17 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Victorinox,483,10 days Returnable,"Monday, 19 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,CAROTE,251,10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/Stainless-Knife-Kitchen-...
...,...,...,...,...,...,...
190,Kai,"1,349",10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/Kai-Premium-Stainless-Se...
191,TOUARETAILS,"1,699",10 days Returnable,"Sunday, 18 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
192,Victorinox,"1,177",10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
193,AGARO,899,10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
194,Kai,"1,349",10 days Returnable,"Saturday, 17 February",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

3. Write a python program to access the search bar and search button on images.google.com and scrape 10
images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [58]:
import selenium
import pandas as pd4
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
#from selenium.common.exceptions import NoSuchElementException
import time
#from selenium.common.exceptions import TimeoutException
#/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea

In [59]:
driver3=webdriver.Chrome()

In [60]:
driver3.get("https://images.google.com/")

In [61]:
search_item=driver3.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search_item.send_keys(input("Enter Item"))

Enter ItemGuitar

In [63]:
search_icon=driver3.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button')
search_icon.click()

In [42]:
fruit_images=[]
f_image=driver3.find_elements(By.XPATH,'//div[@class="fR600b islir"]/img')
for i, img in enumerate(f_image[:10], start=1):
    fruit_images.append(img.get_attribute('href'))
    print(f"Scraped image {i}")

print("Total scraped images:", len(fruit_images))

Scraped image 1
Scraped image 2
Scraped image 3
Scraped image 4
Scraped image 5
Scraped image 6
Scraped image 7
Scraped image 8
Scraped image 9
Scraped image 10
Total scraped images: 10

In [57]:
car_images=[]
c_image=driver3.find_elements(By.XPATH,'//div[@class="fR600b islir"]/img')
for j, img1 in enumerate(c_image[:10], start=1):
    car_images.append(img1.get_attribute('href'))
    print(f"Scraped image {j}")

print("Total scraped images:", len(car_images))

Scraped image 1
Scraped image 2
Scraped image 3
Scraped image 4
Scraped image 5
Scraped image 6
Scraped image 7
Scraped image 8
Scraped image 9
Scraped image 10
Total scraped images: 10

4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com
and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand
Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”,
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the
details is missing then replace it by “- “. Save your results in a dataframe and CSV

In [102]:
import selenium
import pandas as pd4
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import time
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [103]:
driver4=webdriver.Chrome()

In [104]:
driver4.get("https://www.flipkart.com")

In [105]:
search_item=driver4.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input')
search_item.send_keys("Oneplus Nord")

In [106]:
search_icon=driver4.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/button')
search_icon.click()

In [96]:
s_url=[]
url=driver4.find_elements(By.XPATH,'//a[@class="_1fQZEK"]')
for i in url:
    s_url.append(i.get_attribute('href'))
len(s_url)

24

In [62]:
sp_brand=[]
for a in s_url:
    driver4.get(a)
    time.sleep(5)
    try:
        phone_bname=driver4.find_element(By.XPATH,'//span[@class="B_NuCI"]')
        sp_brand.append(phone_bname.text)
    except NoSuchElementException:
        sp_brand.append('Not Present')
print(sp_brand)        
len(sp_brand)

['OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB)  (8 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256 GB)  (8 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)  (6 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)  (6 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Pastel lime, 256 GB)  (8 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256 GB)  (8 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE3 5G (Aqua Surge, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE3 5G (Aqua Surge, 256 GB)  (12 GB RAM)', 'OnePlus Nord 3 5G (Misty Green, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB)  (8 GB RAM)', 'OnePlus Nord CE3 5G (Grey Shimmer, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256 GB)  (8 GB RAM)', 'OnePlus Nord 3 5G (Tempest Gray, 256 GB)  (16 GB RAM)', 'OnePlus Nord 3 5G (Misty Green, 256 GB)  (16 GB RAM)', 'OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128 GB)  (8 GB RAM)', 'OnePlus Nord 3 5G (Tempest Gray, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)  (8 GB RAM)', 'OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)  (8 GB RAM)', 'OnePlus Nord 2T 5G (Jade Fog, 128 GB)  (8 GB RAM)']

24

In [81]:
sp_name=[]
for b in s_url:
    driver4.get(b)
    time.sleep(10)
    try:
        phone_name=driver4.find_element(By.XPATH,'//div[@class="_3dtsli"]/div[2]/div[1]/div[1]/table/tbody/tr[3]/td[2]/ul/li')
        sp_name.append(phone_name.text)
    except TimeoutException as e:
        sp_name.append('Not Present')
print(sp_name)
len(sp_name)

['Nord CE 3 Lite 5G', 'Nord CE 3 Lite 5G', 'Nord CE 3 Lite 5G', 'Nord CE 3 Lite 5G', 'Nord CE 2 Lite 5G', 'Nord CE 3 Lite 5G', 'Nord CE 2 Lite 5G', 'Nord CE 3 Lite 5G', 'Nord CE 3 Lite 5G', 'Nord CE 3 Lite 5G', 'Nord CE3 5G', 'Nord CE3 5G', 'Nord 3 5G', 'Nord CE 3 Lite 5G', 'Nord CE3 5G', 'Nord CE 3 Lite 5G', 'Nord 3 5G', 'Nord 3 5G', 'Nord CE 3 Lite 5G', 'Nord 3 5G', 'Nord CE 2 5G', 'Nord CE 2 5G', 'Nord CE 2 5G', 'Nord 2T 5G']

24

In [82]:
sp_colour=[]
for c in s_url:
    driver4.get(c)
    time.sleep(10)
    try:
        phone_colour=driver4.find_element(By.XPATH,'//div[@class="_3dtsli"]/div[2]/div[1]/div[1]/table/tbody/tr[4]/td[2]/ul/li')
        sp_colour.append(phone_colour.text)        
    except TimeoutException as e:
        sp_colour.append('Not Present')
print(sp_colour)
len(sp_colour)

['Pastel Lime', 'Chromatic Gray', 'Chromatic Gray', 'Pastel Lime', 'Blue Tide', 'Chromatic Gray', 'Black Dusk', 'Pastel lime', 'Chromatic Gray', 'Pastel Lime', 'Aqua Surge', 'Aqua Surge', 'Misty Green', 'Pastel Lime', 'Grey Shimmer', 'Chromatic Gray', 'Tempest Gray', 'Misty Green', 'Chromatic Gray', 'Tempest Gray', 'Bahama Blue', 'Bahama Blue', 'Bahama Blue', 'Jade Fog']

24

In [125]:
data_list = []
phone_pcamera = driver4.find_elements(By.XPATH,'//div[@class="fMghEO"]/ul/li[3]')
for k in phone_pcamera:
    data_list.append(k.text)
sp_Pcamera = [string.split()[0] for string in data_list]
print(sp_Pcamera)
print(len(sp_Pcamera))

['108MP', '108MP', '108MP', '108MP', '108MP', '108MP', '64MP', '108MP', '64MP', '108MP', '50MP', '108MP', '50MP', '50MP', '108MP', '108MP', '50MP', '50MP', '50MP', '64MP', '64MP', '64MP', '50MP', '50MP']
24

In [140]:
sp_RamRom=[]
phone_ramrom=driver4.find_elements(By.XPATH,'//div[@class="fMghEO"]/ul/li[1]')
for j in phone_ramrom:
    sp_RamRom.append(j.text)
len(sp_RamRom)

24

In [143]:
sp_Display = []
phone_display = driver4.find_elements(By.XPATH, '//div[@class="fMghEO"]/ul/li[2]')
for l in phone_display:
    sp_Display.append(l.text.split(" Display")[0])

print(sp_Display)
print(len(sp_Display))

['17.07 cm (6.72 inch)', '17.07 cm (6.72 inch)', '17.07 cm (6.72 inch)', '17.07 cm (6.72 inch)', '17.07 cm (6.72 inch)', '17.07 cm (6.72 inch)', '16.74 cm (6.59 inch)', '17.07 cm (6.72 inch)', '16.74 cm (6.59 inch)', '17.07 cm (6.72 inch)', '17.02 cm (6.7 inch)', '17.07 cm (6.72 inch)', '17.12 cm (6.74 inch)', '17.02 cm (6.7 inch)', '17.07 cm (6.72 inch)', '17.07 cm (6.72 inch)', '17.12 cm (6.74 inch)', '17.12 cm (6.74 inch) Full HD+', '17.12 cm (6.74 inch)', '16.33 cm (6.43 inch)', '16.33 cm (6.43 inch)', '16.33 cm (6.43 inch)', '17.02 cm (6.7 inch)', '17.02 cm (6.7 inch)']
24

In [145]:
sp_Battery = []
phone_battery = driver4.find_elements(By.XPATH, '//div[@class="fMghEO"]/ul/li[4]')
for m in phone_battery:
    sp_Battery.append(m.text.split("Battery")[0])

print(sp_Battery)
print(len(sp_Battery))

['5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '5000 mAh ', '4500 mAh ', '4500 mAh ', '4500 mAh ', '4500 mAh ', '4500 mAh ']
24

In [146]:
sp_Price=[]
phone_price=driver4.find_elements(By.XPATH,'//div[@class="_30jeq3 _1_WHN1"]')
for n in phone_price:
    sp_Price.append(n.text)
print(sp_Price)
len(sp_Price)

['₹20,967', '₹19,430', '₹19,428', '₹20,884', '₹21,249', '₹21,285', '₹18,298', '₹19,938', '₹17,809', '₹19,990', '₹24,599', '₹21,335', '₹28,165', '₹24,398', '₹21,870', '₹19,713', '₹36,000', '₹29,097', '₹37,630', '₹22,495', '₹21,988', '₹21,395', '₹28,990', '₹28,999']

24

In [148]:
#sp_brand=[] sp_name=[] sp_colour=[] data_list = [] sp_RamRom=[] sp_Display = [] sp_Battery = [] sp_Price=[] s_url=[]
df4=pd4.DataFrame({"Phone Brand":sp_brand,"Phone Name":sp_name,"Camera":sp_Pcamera,"Ram & Rom":sp_RamRom,"Display":sp_Display,"Battery":sp_Battery,"Price":sp_Price,"URL":s_url})
df4

,Phone Brand,Phone Name,Camera,Ram & Rom,Display,Battery,Price,URL
0,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹20,967",https://www.flipkart.com/oneplus-nord-ce-3-lit...
1,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,430",https://www.flipkart.com/oneplus-nord-ce-3-lit...
2,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,428",https://www.flipkart.com/oneplus-nord-ce-3-lit...
3,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹20,884",https://www.flipkart.com/oneplus-nord-ce-3-lit...
4,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB) ...",Nord CE 2 Lite 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹21,249",https://www.flipkart.com/oneplus-nord-ce-3-lit...
5,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹21,285",https://www.flipkart.com/oneplus-nord-ce-3-lit...
6,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)...",Nord CE 2 Lite 5G,64MP,6 GB RAM | 128 GB ROM,16.74 cm (6.59 inch),5000 mAh,"₹18,298",https://www.flipkart.com/oneplus-nord-ce-2-lit...
7,"OnePlus Nord CE 3 Lite 5G (Pastel lime, 256 GB...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,938",https://www.flipkart.com/oneplus-nord-ce-3-lit...
8,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",Nord CE 3 Lite 5G,64MP,6 GB RAM | 128 GB ROM,16.74 cm (6.59 inch),5000 mAh,"₹17,809",https://www.flipkart.com/oneplus-nord-ce-2-lit...
9,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,990",https://www.flipkart.com/oneplus-nord-ce-3-lit...
10,"OnePlus Nord CE3 5G (Aqua Surge, 128 GB) (8 G...",Nord CE3 5G,50MP,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch),5000 mAh,"₹24,599",https://www.flipkart.com/oneplus-nord-ce3-5g-a...
11,"OnePlus Nord CE3 5G (Aqua Surge, 256 GB) (12 ...",Nord CE3 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹21,335",https://www.flipkart.com/oneplus-nord-ce-3-lit...
12,"OnePlus Nord 3 5G (Misty Green, 128 GB) (8 GB...",Nord 3 5G,50MP,8 GB RAM | 128 GB ROM,17.12 cm (6.74 inch),5000 mAh,"₹28,165",https://www.flipkart.com/oneplus-nord-3-5g-mis...
13,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB...",Nord CE 3 Lite 5G,50MP,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch),5000 mAh,"₹24,398",https://www.flipkart.com/oneplus-nord-ce3-5g-g...
14,"OnePlus Nord CE3 5G (Grey Shimmer, 128 GB) (8...",Nord CE3 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹21,870",https://www.flipkart.com/oneplus-nord-ce-3-lit...
15,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,713",https://www.flipkart.com/oneplus-nord-ce-3-lit...
16,"OnePlus Nord 3 5G (Tempest Gray, 256 GB) (16 ...",Nord 3 5G,50MP,16 GB RAM | 256 GB ROM,17.12 cm (6.74 inch),5000 mAh,"₹36,000",https://www.flipkart.com/oneplus-nord-3-5g-tem...
17,"OnePlus Nord 3 5G (Misty Green, 256 GB) (16 G...",Nord 3 5G,50MP,8 GB RAM | 128 GB ROM,17.12 cm (6.74 inch) Full HD+,5000 mAh,"₹29,097",https://www.flipkart.com/oneplus-nord-3-5g-tem...
18,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",Nord CE 3 Lite 5G,50MP,16 GB RAM | 256 GB ROM,17.12 cm (6.74 inch),5000 mAh,"₹37,630",https://www.flipkart.com/oneplus-nord-3-5g-mis...
19,"OnePlus Nord 3 5G (Tempest Gray, 128 GB) (8 G...",Nord 3 5G,64MP,8 GB RAM | 128 GB ROM,16.33 cm (6.43 inch),4500 mAh,"₹22,495",https://www.flipkart.com/oneplus-nord-ce-2-5g-...
20,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB) (8...",Nord CE 2 5G,64MP,8 GB RAM | 128 GB ROM,16.33 cm (6.43 inch),4500 mAh,"₹21,988",https://www.flipkart.com/oneplus-nord-ce-2-5g-...
21,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB) (8...",Nord CE 2 5G,64MP,8 GB RAM | 128 GB ROM,16.33 cm (6.43 inch),4500 mAh,"₹21,395",https://www.flipkart.com/oneplus-nord-ce-2-5g-...
22,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB) (8...",Nord CE 2 5G,50MP,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch),4500 mAh,"₹28,990",https://www.flipkart.com/oneplus-nord-ce3-5g-a...
23,"OnePlus Nord 2T 5G (Jade Fog, 128 GB) (8 GB RAM)",Nord 2T 5G,50MP,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch),4500 mAh,"₹28,999",https://www.flipkart.com/oneplus-nord-2t-5g-ja...

In [149]:
df4.to_csv('Smart Phone Data',index=False)

In [150]:
df4=pd4.read_csv('Smart Phone Data')
df4

,Phone Brand,Phone Name,Camera,Ram & Rom,Display,Battery,Price,URL
0,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹20,967",https://www.flipkart.com/oneplus-nord-ce-3-lit...
1,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,430",https://www.flipkart.com/oneplus-nord-ce-3-lit...
2,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,428",https://www.flipkart.com/oneplus-nord-ce-3-lit...
3,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹20,884",https://www.flipkart.com/oneplus-nord-ce-3-lit...
4,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB) ...",Nord CE 2 Lite 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹21,249",https://www.flipkart.com/oneplus-nord-ce-3-lit...
5,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹21,285",https://www.flipkart.com/oneplus-nord-ce-3-lit...
6,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)...",Nord CE 2 Lite 5G,64MP,6 GB RAM | 128 GB ROM,16.74 cm (6.59 inch),5000 mAh,"₹18,298",https://www.flipkart.com/oneplus-nord-ce-2-lit...
7,"OnePlus Nord CE 3 Lite 5G (Pastel lime, 256 GB...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,938",https://www.flipkart.com/oneplus-nord-ce-3-lit...
8,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",Nord CE 3 Lite 5G,64MP,6 GB RAM | 128 GB ROM,16.74 cm (6.59 inch),5000 mAh,"₹17,809",https://www.flipkart.com/oneplus-nord-ce-2-lit...
9,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,990",https://www.flipkart.com/oneplus-nord-ce-3-lit...
10,"OnePlus Nord CE3 5G (Aqua Surge, 128 GB) (8 G...",Nord CE3 5G,50MP,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch),5000 mAh,"₹24,599",https://www.flipkart.com/oneplus-nord-ce3-5g-a...
11,"OnePlus Nord CE3 5G (Aqua Surge, 256 GB) (12 ...",Nord CE3 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹21,335",https://www.flipkart.com/oneplus-nord-ce-3-lit...
12,"OnePlus Nord 3 5G (Misty Green, 128 GB) (8 GB...",Nord 3 5G,50MP,8 GB RAM | 128 GB ROM,17.12 cm (6.74 inch),5000 mAh,"₹28,165",https://www.flipkart.com/oneplus-nord-3-5g-mis...
13,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB...",Nord CE 3 Lite 5G,50MP,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch),5000 mAh,"₹24,398",https://www.flipkart.com/oneplus-nord-ce3-5g-g...
14,"OnePlus Nord CE3 5G (Grey Shimmer, 128 GB) (8...",Nord CE3 5G,108MP,8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹21,870",https://www.flipkart.com/oneplus-nord-ce-3-lit...
15,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",Nord CE 3 Lite 5G,108MP,8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch),5000 mAh,"₹19,713",https://www.flipkart.com/oneplus-nord-ce-3-lit...
16,"OnePlus Nord 3 5G (Tempest Gray, 256 GB) (16 ...",Nord 3 5G,50MP,16 GB RAM | 256 GB ROM,17.12 cm (6.74 inch),5000 mAh,"₹36,000",https://www.flipkart.com/oneplus-nord-3-5g-tem...
17,"OnePlus Nord 3 5G (Misty Green, 256 GB) (16 G...",Nord 3 5G,50MP,8 GB RAM | 128 GB ROM,17.12 cm (6.74 inch) Full HD+,5000 mAh,"₹29,097",https://www.flipkart.com/oneplus-nord-3-5g-tem...
18,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",Nord CE 3 Lite 5G,50MP,16 GB RAM | 256 GB ROM,17.12 cm (6.74 inch),5000 mAh,"₹37,630",https://www.flipkart.com/oneplus-nord-3-5g-mis...
19,"OnePlus Nord 3 5G (Tempest Gray, 128 GB) (8 G...",Nord 3 5G,64MP,8 GB RAM | 128 GB ROM,16.33 cm (6.43 inch),4500 mAh,"₹22,495",https://www.flipkart.com/oneplus-nord-ce-2-5g-...
20,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB) (8...",Nord CE 2 5G,64MP,8 GB RAM | 128 GB ROM,16.33 cm (6.43 inch),4500 mAh,"₹21,988",https://www.flipkart.com/oneplus-nord-ce-2-5g-...
21,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB) (8...",Nord CE 2 5G,64MP,8 GB RAM | 128 GB ROM,16.33 cm (6.43 inch),4500 mAh,"₹21,395",https://www.flipkart.com/oneplus-nord-ce-2-5g-...
22,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB) (8...",Nord CE 2 5G,50MP,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch),4500 mAh,"₹28,990",https://www.flipkart.com/oneplus-nord-ce3-5g-a...
23,"OnePlus Nord 2T 5G (Jade Fog, 128 GB) (8 GB RAM)",Nord 2T 5G,50MP,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch),4500 mAh,"₹28,999",https://www.flipkart.com/oneplus-nord-2t-5g-ja...

5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [38]:
import selenium
import pandas as pd5
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [39]:
driver5=webdriver.Chrome()

In [40]:
driver5.get("https://maps.google.com/")

In [41]:
location=driver5.find_element(By.XPATH,'/html/body/div[1]/div[3]/div[8]/div[3]/div[1]/div[1]/div/div[2]/form/input')
location.send_keys("Patia,Bhubaneswar")

In [42]:
search_icon=driver5.find_element(By.XPATH,'/html/body/div[1]/div[3]/div[8]/div[3]/div[1]/div[1]/div/div[2]/div[1]/button')
search_icon.click()

In [43]:
url=driver5.current_url
coordinates = url.split('@')[1].split(',')[0:2]
latitude = coordinates[0]
longitude = coordinates[1]
print('Latitude:', latitude)
print('Longitude:', longitude)

Latitude: 20.3514683
Longitude: 85.7831276

6. Write a program to scrap all the available details of best gaming laptops from digit.in.

In [99]:
import selenium
import pandas as pd6
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [100]:
driver6=webdriver.Chrome()

In [101]:
driver6.get("https://www.digit.in/")

In [103]:
search_item=driver6.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div/div/div[2]/form/input[1]')
search_item.send_keys("Gaming Laptops")

In [104]:
search_icon=driver6.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div/div/div[2]/form/button')
search_icon.click()

In [105]:
laptop_name=[]
l_name=driver6.find_elements(By.XPATH,'//h3[@class=" text-clamp text-clamp-2"]/a')
for m in l_name:
    laptop_name.append(m.text)
len(laptop_name)

6

In [109]:
laptop_price=[]
l_price=driver6.find_elements(By.XPATH,'//div[@class="border-top pt10 pr10 pl10 pb10 rh-flex-center-align abposbot"]')
for n in l_price:
    laptop_price.append(n.text)
for i in range(len(laptop_price)):
    if laptop_price[i] == "":
        laptop_price[i] = "-"
print(laptop_price)
len(laptop_price)

['₹79,831.00', 'out of stock\nBuy Now\nAmazon.in', '₹174,990.00', '-', '₹328,800.00', 'out of stock\nBuy Now\nAmazon.in']

6

In [117]:
laptop_url=[]
laptop_url=driver6.find_elements(By.XPATH,'//a[@class="img-centered-flex rh-flex-justify-center rh-flex-center-align"]')
for o in laptop_url:
    print(o.get_attribute('href'))
len(laptop_url)

https://www.digit.in/laptops/lenovo-ideapad-gaming-3-15iah7-price-341574.html
https://www.digit.in/laptops/lenovo-ideapad-gaming-3i-price-319434.html
https://www.digit.in/laptops/alienware-x14-gaming-laptop-price-318804.html
https://www.digit.in/laptops/msi-gaming-raider-ge76-12th-gen-core-i9-12900hk-2022-price-287791.html
https://www.digit.in/laptops/lenovo-legion-7-ryzen-9-5900hx-2022-price-288225.html
https://www.digit.in/laptops/dell-15-2021-i5-10200h-price-287917.html

6

In [118]:
df6=pd6.DataFrame({'Laptop Name':laptop_name,'Price':laptop_price,'URL':laptop_url})
df6

,Laptop Name,Price,URL
0,Lenovo IdeaPad Gaming 3 15IAH7,"₹79,831.00",<selenium.webdriver.remote.webelement.WebEleme...
1,Lenovo IdeaPad Gaming 3i,out of stock\nBuy Now\nAmazon.in,<selenium.webdriver.remote.webelement.WebEleme...
2,Alienware x14 Gaming Laptop,"₹174,990.00",<selenium.webdriver.remote.webelement.WebEleme...
3,MSI Gaming Raider,-,<selenium.webdriver.remote.webelement.WebEleme...
4,Lenovo Legion 7,"₹328,800.00",<selenium.webdriver.remote.webelement.WebEleme...
5,Dell 15 (2021) i5-10200H,out of stock\nBuy Now\nAmazon.in,<selenium.webdriver.remote.webelement.WebEleme...

7. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped:
“Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [93]:
import selenium
from selenium.common.exceptions import StaleElementReferenceException
import pandas as pd7
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [94]:
driver7=webdriver.Chrome()

In [95]:
time.sleep(5)
driver7.get("https://www.forbes.com./")

In [96]:
three_lines=driver7.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[1]/div[1]/div')
three_lines.click()
time.sleep(3)

In [99]:
billionaires=driver7.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[1]/div[1]/div/div[2]/ul/li[2]/div[1]/span')
billionaires.click()

In [100]:
w_billionaires=driver7.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[1]/div[1]/div/div[2]/ul/li[2]/div[2]/div[3]/ul/li[1]')
w_billionaires.click()

In [102]:
try:
    #Extracting ranks...
    ranks=[]
    b_rank=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[1]/div')
    for a in b_rank:
        ranks.append(a.text)
    print("Length of the ranks",len(ranks))
    #Extracting names...
    names=[]
    b_name=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[2]/div')
    for b in b_name:
        names.append(b.text)
    print("Length of the names",len(names))
except StaleElementReferenceException as e:
    driver7.refresh()
    ranks=[]
    b_rank=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[1]/div')
    for a in b_rank:
        ranks.append(a.text)
    #print("Length of the ranks",len(ranks))
    names=[]
    b_name=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[2]/div')
    for b in b_name:
        names.append(b.text)
    #print("Length of the names",len(names))

Length of the ranks 200
Length of the names 200

In [103]:
try:
    #Extracting NetWorth...
    netWorths=[]
    b_NW=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[3]/div')
    for c in b_NW:
        netWorths.append(c.text)
    print("Length of the names",len(netWorths))
    #Extracting Age...
    ages=[]
    b_ages=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[4]/div')
    for d in b_ages:
        ages.append(d.text)
    print("Length of the ages",len(ages))
except StaleElementReferenceException as f:
    driver7.refresh()
    netWorths=[]
    b_NW=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[3]/div')
    for c in b_NW:
        netWorths.append(c.text)
    print("Length of the names",len(netWorths))
    ages=[]
    b_ages=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[4]/div')
    for d in b_ages:
        ages.append(d.text)
    print("Length of the ages",len(ages))

Length of the names 200
Length of the ages 200

In [104]:
try:
    #Extracting Citizenship...
    citizenships=[]
    b_citizen=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[5]')
    for e in b_citizen:
        citizenships.append(c.text)
    print("Length of the names",len(citizenships))
except StaleElementsReferenceException as g:
    driver7.refresh()
    citizenships=[]
    b_citizen=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[5]')
    for e in b_citizen:
        citizenships.append(c.text)
    print("Length of the names",len(citizenships))

Length of the names 200

In [109]:
try:
    #Extracting Citizenship...
    b_sources=[]
    b_source=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[6]/div')
    for f in b_source:
        b_sources.append(f.text)
    print("Length of the names",len(b_sources))
    #Extracting Industry...
    industries=[]
    b_industry=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[7]/div')
    for g in b_industry:
        industries.append(g.text)
    print("Length of the names",len(industries))
except StaleElementReferenceException as h:
    b_sources=[]
    b_source=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[6]/div')
    for f in b_source:
        b_sources.append(f.text)
    print("Length of the names",len(b_sources))
    industries=[]
    b_industry=driver7.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]/div[7]/div')
    for g in b_industry:
        industries.append(g.text)
    print("Length of the names",len(industries))

Length of the names 200
Length of the names 200

In [110]:
#Making DataFrame
dfx=pd7.DataFrame({"Ranks":ranks,"Names":names,"NetWorth":netWorths,"Age":ages,"Citizenship":citizenships,"Source":b_sources,"Industry":industries})
dfx

,Ranks,Names,NetWorth,Age,Citizenship,Source,Industry
0,1,Bernard Arnault & family,$211 B,74,$9.6 B,LVMH,Fashion & Retail
1,2,Elon Musk,$180 B,51,$9.6 B,"Tesla, SpaceX",Automotive
2,3,Jeff Bezos,$114 B,59,$9.6 B,Amazon,Technology
3,4,Larry Ellison,$107 B,78,$9.6 B,Oracle,Technology
4,5,Warren Buffett,$106 B,92,$9.6 B,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
195,195,Jin Baofang,$9.6 B,70,$9.6 B,Solar panels,Energy
196,195,Luo Liguo & family,$9.6 B,67,$9.6 B,Chemicals,Manufacturing
197,195,Marijke Mars,$9.6 B,58,$9.6 B,"Candy, pet food",Food & Beverage
198,195,Pamela Mars,$9.6 B,62,$9.6 B,"Candy, pet food",Food & Beverage
199,195,Valerie Mars,$9.6 B,64,$9.6 B,"Candy, pet food",Food & Beverage

In [111]:
#Saving above DataFrame to CSV file format
dfx.to_csv('Billionaires Deatail',index=False)

In [112]:
#To fetch that CSV file
dfx=pd7.read_csv('Billionaires Deatail')
dfx

,Ranks,Names,NetWorth,Age,Citizenship,Source,Industry
0,1,Bernard Arnault & family,$211 B,74.0,$9.6 B,LVMH,Fashion & Retail
1,2,Elon Musk,$180 B,51.0,$9.6 B,"Tesla, SpaceX",Automotive
2,3,Jeff Bezos,$114 B,59.0,$9.6 B,Amazon,Technology
3,4,Larry Ellison,$107 B,78.0,$9.6 B,Oracle,Technology
4,5,Warren Buffett,$106 B,92.0,$9.6 B,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
195,195,Jin Baofang,$9.6 B,70.0,$9.6 B,Solar panels,Energy
196,195,Luo Liguo & family,$9.6 B,67.0,$9.6 B,Chemicals,Manufacturing
197,195,Marijke Mars,$9.6 B,58.0,$9.6 B,"Candy, pet food",Food & Beverage
198,195,Pamela Mars,$9.6 B,62.0,$9.6 B,"Candy, pet food",Food & Beverage
199,195,Valerie Mars,$9.6 B,64.0,$9.6 B,"Candy, pet food",Food & Beverage

8. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted
from any YouTube Video.

In [57]:
import selenium
import pandas as pd8
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
import time
#//yt-formatted-string[@class=" style-scope ytd-comment-renderer style-scope ytd-comment-renderer"]

In [58]:
driver8=webdriver.Chrome()   
driver8.get("https://www.youtube.com/watch?v=Adw32Q_gm4U&t=30s")
#time.sleep(10)
#delay=10    
scroll_pause_time = 10
last_height = driver8.execute_script("return document.documentElement.scrollHeight")
while True:
    driver8.execute_script("window.scrollTo(0, document.documentElement.scrollHeight);")
    time.sleep(scroll_pause_time)
    new_height = driver8.execute_script("return document.documentElement.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

In [69]:
try:
    delay=20
    s_Eid=[]
    WebDriverWait(driver8,delay).until(EC.presence_of_element_located((By.CSS_SELECTOR,'#author-text > yt-formatted-string')))
    sid=driver8.find_elements(By.CSS_SELECTOR,'#author-text > yt-formatted-string')
    for m in sid[:150]:
        s_Eid.append(m.text)
    print(len(s_Eid))
    #print(s_Eid)
except TimeoutException as e:
    print("Exception Raised",e)
    s_Eid=[]
    WebDriverWait(driver8,delay).until(EC.presence_of_element_located((By.CSS_SELECTOR,'#author-text > yt-formatted-string')))
    sid=driver8.find_elements(By.CSS_SELECTOR,'#author-text > yt-formatted-string')
    for m in sid[:150]:
        s_Eid.append(m.text)
    print(len(s_Eid))
    #print(s_Eid)

150

In [86]:
try:
    delay=20
    s_comment=[]
    WebDriverWait(driver8,delay).until(EC.presence_of_element_located((By.CSS_SELECTOR,'#content-text > span')))
    comment=driver8.find_elements(By.CSS_SELECTOR,'#content-text > span')
    for n in comment[:150]:
        s_comment.append(n.text)
    for i in range(len(s_comment)):
        if s_comment[i] == "":
            s_comment[i] = "-"
    print(len(s_comment))
    #print(s_comment)
except TimeoutException as e:
    print("Exception Raised",e)
    s_comment=[]
    WebDriverWait(driver8,delay).until(EC.presence_of_element_located((By.CSS_SELECTOR,'#content-text > span')))
    comment=driver8.find_elements(By.CSS_SELECTOR,'#content-text > span')
    for n in comment[:150]:
        s_comment.append(n.text)
    for i in range(len(s_comment)):
        if s_comment[i] == "":
            s_comment[i] = "-"
    print(len(s_comment))
    #print(s_comment)

150

In [83]:
try:
    delay=20
    comment_time=[]
    WebDriverWait(driver8,delay).until(EC.presence_of_element_located((By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]/a')))
    time=driver8.find_elements(By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]/a')
    for o in time[:150]:
        comment_time.append(o.text)
    print(len(comment_time))
    #print(s_comment)
except TimeoutException as e:
    print("Exception Raised",e)
    delay=20
    comment_time=[]
    WebDriverWait(driver8,delay).until(EC.presence_of_element_located((By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]/a')))
    time=driver8.find_elements(By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]/a')
    for o in time[:150]:
        comment_time.append(o.text)
    print(len(comment_time))
    #print(s_comment)

150

In [88]:
try:
    delay=20
    comment_vote=[]
    WebDriverWait(driver8,delay).until(EC.presence_of_element_located((By.CSS_SELECTOR,'#vote-count-middle')))
    vote=driver8.find_elements(By.CSS_SELECTOR,'#vote-count-middle')
    for p in vote[:150]:
        comment_vote.append(p.text)
    for j in range(len(s_comment)):
        if comment_vote[j] == "":
            comment_vote[j] = "-"
    print(len(comment_vote))
    #print(s_comment)
except TimeoutException as e:
    print("Exception Raised",e)
    comment_vote=[]
    WebDriverWait(driver8,delay).until(EC.presence_of_element_located((By.CSS_SELECTOR,'#vote-count-middle')))
    vote=driver8.find_elements(By.CSS_SELECTOR,'#vote-count-middle')
    for p in vote[:150]:
        comment_vote.append(p.text)
    for j in range(len(s_comment)):
        if comment_vote[j] == "":
            comment_vote[j] = "-"
    print(len(comment_vote))
    #print(s_comment)

150

In [89]:
df8=pd8.DataFrame({"Commenter Id":s_Eid,"Comment":s_comment,"Vote":comment_vote,"Time":comment_time})
df8

,Commenter Id,Comment,Vote,Time
0,@ayushmaanmayur7621,Rajesh bhaiya aap jaldi se thik ho jaen....Shr...,32,1 day ago
1,@vilenYtgaming,Get well soon Mr.Rajesh jii,8,1 day ago
2,@AjayKumar-wf5wb,you're great man,19,1 day ago
3,@immortalgamer_5531,भोले बाबा की कृपा आप पर और आपके परिवार पर हमेश...,15,1 day ago
4,@akumarboy,Get well soon Rajesh Uncle,22,1 day ago
...,...,...,...,...
145,@sharadkatkade1822,-,-,1 day ago
146,@rajkumarvishwakarma9893,-,-,1 day ago
147,@ranjeetthakar1479,-,1,1 day ago
148,@MohdAlfaizAnsari,First,2,1 day ago
149,@salimhooda3918,Pathalgaon,-,1 day ago

In [90]:
df8.to_csv('Youtube Data',index=False)

In [91]:
df8=pd8.read_csv('Youtube Data')
df8

,Commenter Id,Comment,Vote,Time
0,@ayushmaanmayur7621,Rajesh bhaiya aap jaldi se thik ho jaen....Shr...,32,1 day ago
1,@vilenYtgaming,Get well soon Mr.Rajesh jii,8,1 day ago
2,@AjayKumar-wf5wb,you're great man,19,1 day ago
3,@immortalgamer_5531,भोले बाबा की कृपा आप पर और आपके परिवार पर हमेश...,15,1 day ago
4,@akumarboy,Get well soon Rajesh Uncle,22,1 day ago
...,...,...,...,...
145,@sharadkatkade1822,-,-,1 day ago
146,@rajkumarvishwakarma9893,-,-,1 day ago
147,@ranjeetthakar1479,-,1,1 day ago
148,@MohdAlfaizAnsari,First,2,1 day ago
149,@salimhooda3918,Pathalgaon,-,1 day ago

9. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in
“London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall
reviews, privates from price, dorms from price, facilities and property description.

In [41]:
import selenium
import pandas as pd9
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time
from selenium.common.exceptions import NoSuchElementException

In [42]:
driver9=webdriver.Chrome()

In [43]:
driver9.get("https://www.hostelworld.com/")

In [44]:
search_city=driver9.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[1]/div/div[2]/input')
search_city.send_keys('London')

In [45]:
select_city=driver9.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[2]/div/ul/li[2]/button')
select_city.click()

In [46]:
search_button=driver9.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[5]/button[2]')
search_button.click()

In [18]:
h_name=[]
hotel=driver9.find_elements(By.XPATH,'//div[@class="property-info-header"]/div[1]/span')
for s in hotel:
    h_name.append(s.text)
print(h_name)
len(h_name)

["Wombat's City Hostel London", 'Palmers Lodge - Swiss Cottage', "St Christopher's Village", 'NX London Hostel', 'Urbany Hostel London', 'Onefam Notting Hill', 'Generator London', 'Onefam Waterloo', 'Astor Hyde Park', 'Safestay London Elephant & Castle', 'Astor Museum Inn', 'No.8 Seven Sisters', 'No.8 Willesden Hostel London', 'Clink261', 'Smart Russell Square Hostel', 'Safestay London Kensington Holland Park', 'YHA London Oxford Street', 'Smart Hyde Park Inn Hostel', 'Destinations Hostels @ The Gallery', 'Hostelle - women only hostel London', 'Queen Elizabeth Chelsea', 'Prime Backpackers Angel', 'Kabannas London St Pancras', 'London Backpackers', 'Smart Camden Inn Hostel', 'Astor Kensington', "St Christopher's Hammersmith", 'Astor Victoria', 'Phoenix Hostel', 'Barmy Badger Backpackers']

30

In [19]:
h_distance=[]
distance=driver9.find_elements(By.XPATH,'//div[@class="property-distance"]/span[2]')
for t in distance:
    h_distance.append(t.text)
print(h_distance)
len(h_distance)

['- 3.6km from city centre', '- 6.5km from city centre', '- 1.8km from city centre', '- 6.1km from city centre', '- 5.4km from city centre', '- 5.5km from city centre', '- 3km from city centre', '- 0.7km from city centre', '- 4.3km from city centre', '- 1.7km from city centre', '- 2.2km from city centre', '- 9km from city centre', '- 10km from city centre', '- 3.2km from city centre', '- 2.6km from city centre', '- 5.8km from city centre', '- 2.1km from city centre', '- 5km from city centre', '- 1.7km from city centre', '- 5.1km from city centre', '- 5.7km from city centre', '- 3.6km from city centre', '- 3.3km from city centre', '- 11.9km from city centre', '- 4.4km from city centre', '- 4.9km from city centre', '- 7.5km from city centre', '- 1.8km from city centre', '- 4.2km from city centre', '- 5.5km from city centre']

30

In [20]:
h_ratings=[]
ratings=driver9.find_elements(By.XPATH,'//div[@class="property-info-header"]/div[2]/div[1]/div[1]/span[1]')
for u in ratings:
    h_ratings.append(u.text)
print(h_ratings)
len(ratings)

['9.1', '8.8', '7.8', '8.9', '9.5', '9.6', '7.5', '9.6', '8.2', '7.2', '8.3', '7.7', '7.2', '7.9', '7.6', '7.0', '9.0', '7.8', '9.1', '8.8', '7.5', '8.5', '8.2', '8.1', '8.3', '8.6', '7.7', '7.3', '6.3', '9.1']

30

In [21]:
h_reviews=[]
review=driver9.find_elements(By.XPATH,'//div[@class="review"]/span')
for v in review:
    h_reviews.append(v.text)
print(h_reviews)
len(h_reviews)

['(15901)', '(15972)', '(12873)', '(2146)', '(1125)', '(2593)', '(8082)', '(135)', '(12327)', '(5278)', '(9455)', '(4178)', '(5201)', '(515)', '(10207)', '(1783)', '(4703)', '(6800)', '(317)', '(116)', '(3687)', '(871)', '(2977)', '(4568)', '(3143)', '(6595)', '(4389)', '(15098)', '(4624)', '(2041)']

30

In [22]:
h_Oreviews=[]
oreview=driver9.find_elements(By.XPATH,'//div[@class="property-info-header"]/div[2]/div[1]/div[1]/span[2]')
for w in oreview:
    h_Oreviews.append(w.text)
print(h_Oreviews)
len(h_Oreviews)

['Superb', 'Fabulous', 'Very Good', 'Fabulous', 'Superb', 'Superb', 'Very Good', 'Superb', 'Fabulous', 'Very Good', 'Fabulous', 'Very Good', 'Very Good', 'Very Good', 'Very Good', 'Very Good', 'Superb', 'Very Good', 'Superb', 'Fabulous', 'Very Good', 'Fabulous', 'Fabulous', 'Fabulous', 'Fabulous', 'Fabulous', 'Very Good', 'Very Good', 'Good', 'Superb']

30

In [68]:
h_Pprice=[]
private_price=driver9.find_elements(By.XPATH,'//div[@class="property-accommodation-prices"]/div[1]')
for a in private_price:
    h_Pprice.append(a.text)
print(h_Pprice)
len(h_Pprice)

['-30%\nPrivates From\n₹17,160\n₹12,012', 'No Privates Available', 'No Privates Available', '-20%\nPrivates From\n₹14,487\n₹11,590', 'No Privates Available', 'Privates From\n₹8,945', 'Privates From\n₹11,357', 'No Privates Available', 'No Privates Available', 'Privates From\n₹19,552', 'Privates From\n₹10,753', 'No Privates Available', 'Privates From\n₹3,137', 'Privates From\n₹10,363', 'No Privates Available', 'No Privates Available', 'Privates From\n₹13,267', 'Privates From\n₹10,196', 'No Privates Available', 'No Privates Available', 'No Privates Available', 'No Privates Available', 'No Privates Available', 'No Privates Available', 'No Privates Available', '-10%\nPrivates From\n₹10,753\n₹9,678', 'No Privates Available', 'Privates From\n₹10,020', 'No Privates Available', 'Privates From\n₹6,843']

30

In [69]:
h_Dprice=[]
dorm_price=driver9.find_elements(By.XPATH,'//div[@class="property-accommodation-prices"]/div[2]')
for b in dorm_price:
    h_Dprice.append(b.text)
print(h_Dprice)
len(h_Dprice)

['No Dorms Available', '-26%\nDorms From\n₹3,101\n₹2,295', '-10%\nDorms From\n₹4,252\n₹3,827', '-15%\nDorms From\n₹3,025\n₹2,571', 'Dorms From\n₹2,953', 'Dorms From\n₹2,490', 'Dorms From\n₹3,058', 'Dorms From\n₹4,112', '-10%\nDorms From\n₹2,154\n₹1,939', 'Dorms From\n₹2,114', 'Dorms From\n₹2,374', 'Dorms From\n₹1,042', 'Dorms From\n₹920', 'Dorms From\n₹2,947', 'Dorms From\n₹1,829', 'Dorms From\n₹1,771', 'No Dorms Available', 'Dorms From\n₹1,515', 'Dorms From\n₹3,626', 'Dorms From\n₹2,584', 'Dorms From\n₹1,681', 'Dorms From\n₹3,177', '-20%\nDorms From\n₹3,806\n₹3,044', 'Dorms From\n₹1,466', 'Dorms From\n₹2,174', '-10%\nDorms From\n₹2,210\n₹1,989', '-10%\nDorms From\n₹1,926\n₹1,734', 'Dorms From\n₹1,746', '-5%\nDorms From\n₹1,484\n₹1,410', 'No Dorms Available']

30

In [26]:
h_url=[]
url=driver9.find_elements(By.XPATH,'//a[@class="property-card-container horizontal"]')
for x in url:
    h_url.append(x.get_attribute('href'))
len(h_url)

30

In [34]:
h_facilities=[]
for z in h_url:
    driver9.get(z)
    time.sleep(5)
    try:
        facility=driver9.find_element(By.XPATH,'//div[@class="facilities-container"]/ul/li/ul/li')
        h_facilities.append(facility.text)
    except NoSuchElementException:
        h_facilities.append('Not Present')
len(h_facilities)

30

In [28]:
h_descriptions=[]
for y in h_url:
    driver9.get(y)
    time.sleep(5)
    try:
        description=driver9.find_element(By.XPATH,'//div[@class="description-container"]/div[1]/div[2]')
        h_descriptions.append(description.text)
    except NoSuchElementException:
        h_descriptions.append('Not Present')
len(h_descriptions)

30

In [71]:
#h_name=[] h_distance=[] h_ratings=[] h_reviews=[] h_Oreviews=[] h_Pprice=[] h_Dprice=[] h_facilities=[] h_descriptions=[]
df9=pd9.DataFrame({"Hotel Name":h_name,"Distance":h_distance,"Ratings":h_ratings,"Reviews":h_reviews,"Overviews":h_Oreviews,"Private Price":h_Pprice,"Dorm price":h_Dprice,"Facilities":h_facilities,"Description":h_descriptions})
df9

,Hotel Name,Distance,Ratings,Reviews,Overviews,Private Price,Dorm price,Facilities,Description
0,Wombat's City Hostel London,- 3.6km from city centre,9.1,(15901),Superb,"-30%\nPrivates From\n₹17,160\n₹12,012",No Dorms Available,Linen Included,A safe haven in the middle of the metropolis: ...
1,Palmers Lodge - Swiss Cottage,- 6.5km from city centre,8.8,(15972),Fabulous,No Privates Available,"-26%\nDorms From\n₹3,101\n₹2,295",Linen Included,Palmers Lodge Swiss Cottage is set in what one...
2,St Christopher's Village,- 1.8km from city centre,7.8,(12873),Very Good,No Privates Available,"-10%\nDorms From\n₹4,252\n₹3,827",Linen Included,Hostelworld visitors have said St Christopher'...
3,NX London Hostel,- 6.1km from city centre,8.9,(2146),Fabulous,"-20%\nPrivates From\n₹14,487\n₹11,590","-15%\nDorms From\n₹3,025\n₹2,571",Free Breakfast,Welcome to NX London Hostel!\n\nPLEASE READ IN...
4,Urbany Hostel London,- 5.4km from city centre,9.5,(1125),Superb,No Privates Available,"Dorms From\n₹2,953",Linen Included,"Welcome to Urbany Hostel London, our first int..."
5,Onefam Notting Hill,- 5.5km from city centre,9.6,(2593),Superb,"Privates From\n₹8,945","Dorms From\n₹2,490",Linen Included,The perfect place for solo travelers to connec...
6,Generator London,- 3km from city centre,7.5,(8082),Very Good,"Privates From\n₹11,357","Dorms From\n₹3,058",Linen Included,Hostelworld guests have said Generator Hostel ...
7,Onefam Waterloo,- 0.7km from city centre,9.6,(135),Superb,No Privates Available,"Dorms From\n₹4,112",Linen Included,Come join us at our newest Onefam location in ...
8,Astor Hyde Park,- 4.3km from city centre,8.2,(12327),Fabulous,No Privates Available,"-10%\nDorms From\n₹2,154\n₹1,939",Linen Included,Note: 18-40 yrs old only. Astor Hyde Park won ...
9,Safestay London Elephant & Castle,- 1.7km from city centre,7.2,(5278),Very Good,"Privates From\n₹19,552","Dorms From\n₹2,114",Linen Included,Safestay at Elephant and Castle is located in ...
10,Astor Museum Inn,- 2.2km from city centre,8.3,(9455),Fabulous,"Privates From\n₹10,753","Dorms From\n₹2,374",Linen Included,Note: 18-40 yrs old only. Astor Museum won 1st...
11,No.8 Seven Sisters,- 9km from city centre,7.7,(4178),Very Good,No Privates Available,"Dorms From\n₹1,042",Linen Included,"For Great Facilities, Comfort & Affordability ..."
12,No.8 Willesden Hostel London,- 10km from city centre,7.2,(5201),Very Good,"Privates From\n₹3,137",Dorms From\n₹920,Linen Included,At No.8 we take pride in our Customer Service ...
13,Clink261,- 3.2km from city centre,7.9,(515),Very Good,"Privates From\n₹10,363","Dorms From\n₹2,947",Linen Included,Clink261 is near King's Cross St Pancras stati...
14,Smart Russell Square Hostel,- 2.6km from city centre,7.6,(10207),Very Good,No Privates Available,"Dorms From\n₹1,829",Linen Included,Many Hostelworld guests who visit Smart Russel...
15,Safestay London Kensington Holland Park,- 5.8km from city centre,7.0,(1783),Very Good,No Privates Available,"Dorms From\n₹1,771",Linen Included,Safestay Holland Park\n\nSafestay Holland Park...
16,YHA London Oxford Street,- 2.1km from city centre,9.0,(4703),Superb,"Privates From\n₹13,267",No Dorms Available,Linen Included,YHA London Oxford Street is all about location...
17,Smart Hyde Park Inn Hostel,- 5km from city centre,7.8,(6800),Very Good,"Privates From\n₹10,196","Dorms From\n₹1,515",Linen Included,Smart Hyde Park Inn Hostel is perfectly locate...
18,Destinations Hostels @ The Gallery,- 1.7km from city centre,9.1,(317),Superb,No Privates Available,"Dorms From\n₹3,626",Free Breakfast,"We are back, we previously operated near Londo..."
19,Hostelle - women only hostel London,- 5.1km from city centre,8.8,(116),Fabulous,No Privates Available,"Dorms From\n₹2,584",Linen Included,Hostelle is the first and only all-women hoste...
20,Queen Elizabeth Chelsea,- 5.7km from city centre,7.5,(3687),Very Good,No Privates Available,"Dorms From\n₹1,681",Linen Included,PLEASE NOTE WE ONLY ACCEPT GUESTS FROM THE AGE...
21,Prime Backpackers Angel,- 3.6km from city centre,8.5,(871),Fabulous,No Privates Available,"Dorms From\n₹3,177",Linen Included,The hostel is housed in a historic building in...
22,Kabannas London St Pancras,- 3.3km from city centre,8.2,(2977),Fabulous,No Privates Available,"-20%\nDorms From\n₹3,806\n₹3,044",Linen Included,Kabannas London St Pancras has friendly recept...
23,London Backpackers,- 11.9km from city centre,8.1,(4568),Fabulous,No Privates Available,"Dorms From\n₹1,466",Linen Included,IMPORTANT NOTICE: \n\nThis hostel is for 18 - ...
24,Smart Camden Inn Hostel,- 4.4km from city centre,8.3,(3143),Fabulous,No Privates Available,"Dorms From\n₹2,174",Linen Included,"Located in the middle of Camden Town, we’re th..."
25,Astor Kensington,- 4.9km from city centre,8.6,(6595),Fabulous,"-10%\nPrivates From\n₹10,753\n₹9,678","-10%\nDorms From\n₹2,210\n₹1,989",Linen Included,Note: 18-40 yrs old only. Astor Kensington won...
26,St Christopher's Hammersmith,- 7.5km from city centre,7.7,(4389),Very Good,No Privates Available,"-10%\nDorms From\n₹1,926\n₹1,734",Linen Included,"The friendly, attentive, and welcoming staff o..."
27,Astor Victoria,- 1.8km from city centre,7.3,(15098),Very Good,"Privates From\n₹10,020","Dorms From\n₹1,746",Linen Included,Note: 18-40 yrs old only. Astor Victoria won 1...
28,Phoenix Hostel,- 4.2km from city centre,6.3,(4624),Good,No Privates Available,"-5%\nDorms From\n₹1,484\n₹1,410",Linen Included,"The Phoenix Bar & Hostel, housed in a homely E..."
29,Barmy Badger Backpackers,- 5.5km from city centre,9.1,(2041),Superb,"Privates From\n₹6,843",No Dorms Available,Free Breakfast,The Badger is unique for London in that we hav...

In [72]:
df9.to_csv('London Hotel Data',index=False)

In [73]:
df9=pd9.read_csv('London Hotel Data')
df9

,Hotel Name,Distance,Ratings,Reviews,Overviews,Private Price,Dorm price,Facilities,Description
0,Wombat's City Hostel London,- 3.6km from city centre,9.1,(15901),Superb,"-30%\nPrivates From\n₹17,160\n₹12,012",No Dorms Available,Linen Included,A safe haven in the middle of the metropolis: ...
1,Palmers Lodge - Swiss Cottage,- 6.5km from city centre,8.8,(15972),Fabulous,No Privates Available,"-26%\nDorms From\n₹3,101\n₹2,295",Linen Included,Palmers Lodge Swiss Cottage is set in what one...
2,St Christopher's Village,- 1.8km from city centre,7.8,(12873),Very Good,No Privates Available,"-10%\nDorms From\n₹4,252\n₹3,827",Linen Included,Hostelworld visitors have said St Christopher'...
3,NX London Hostel,- 6.1km from city centre,8.9,(2146),Fabulous,"-20%\nPrivates From\n₹14,487\n₹11,590","-15%\nDorms From\n₹3,025\n₹2,571",Free Breakfast,Welcome to NX London Hostel!\n\nPLEASE READ IN...
4,Urbany Hostel London,- 5.4km from city centre,9.5,(1125),Superb,No Privates Available,"Dorms From\n₹2,953",Linen Included,"Welcome to Urbany Hostel London, our first int..."
5,Onefam Notting Hill,- 5.5km from city centre,9.6,(2593),Superb,"Privates From\n₹8,945","Dorms From\n₹2,490",Linen Included,The perfect place for solo travelers to connec...
6,Generator London,- 3km from city centre,7.5,(8082),Very Good,"Privates From\n₹11,357","Dorms From\n₹3,058",Linen Included,Hostelworld guests have said Generator Hostel ...
7,Onefam Waterloo,- 0.7km from city centre,9.6,(135),Superb,No Privates Available,"Dorms From\n₹4,112",Linen Included,Come join us at our newest Onefam location in ...
8,Astor Hyde Park,- 4.3km from city centre,8.2,(12327),Fabulous,No Privates Available,"-10%\nDorms From\n₹2,154\n₹1,939",Linen Included,Note: 18-40 yrs old only. Astor Hyde Park won ...
9,Safestay London Elephant & Castle,- 1.7km from city centre,7.2,(5278),Very Good,"Privates From\n₹19,552","Dorms From\n₹2,114",Linen Included,Safestay at Elephant and Castle is located in ...
10,Astor Museum Inn,- 2.2km from city centre,8.3,(9455),Fabulous,"Privates From\n₹10,753","Dorms From\n₹2,374",Linen Included,Note: 18-40 yrs old only. Astor Museum won 1st...
11,No.8 Seven Sisters,- 9km from city centre,7.7,(4178),Very Good,No Privates Available,"Dorms From\n₹1,042",Linen Included,"For Great Facilities, Comfort & Affordability ..."
12,No.8 Willesden Hostel London,- 10km from city centre,7.2,(5201),Very Good,"Privates From\n₹3,137",Dorms From\n₹920,Linen Included,At No.8 we take pride in our Customer Service ...
13,Clink261,- 3.2km from city centre,7.9,(515),Very Good,"Privates From\n₹10,363","Dorms From\n₹2,947",Linen Included,Clink261 is near King's Cross St Pancras stati...
14,Smart Russell Square Hostel,- 2.6km from city centre,7.6,(10207),Very Good,No Privates Available,"Dorms From\n₹1,829",Linen Included,Many Hostelworld guests who visit Smart Russel...
15,Safestay London Kensington Holland Park,- 5.8km from city centre,7.0,(1783),Very Good,No Privates Available,"Dorms From\n₹1,771",Linen Included,Safestay Holland Park\n\nSafestay Holland Park...
16,YHA London Oxford Street,- 2.1km from city centre,9.0,(4703),Superb,"Privates From\n₹13,267",No Dorms Available,Linen Included,YHA London Oxford Street is all about location...
17,Smart Hyde Park Inn Hostel,- 5km from city centre,7.8,(6800),Very Good,"Privates From\n₹10,196","Dorms From\n₹1,515",Linen Included,Smart Hyde Park Inn Hostel is perfectly locate...
18,Destinations Hostels @ The Gallery,- 1.7km from city centre,9.1,(317),Superb,No Privates Available,"Dorms From\n₹3,626",Free Breakfast,"We are back, we previously operated near Londo..."
19,Hostelle - women only hostel London,- 5.1km from city centre,8.8,(116),Fabulous,No Privates Available,"Dorms From\n₹2,584",Linen Included,Hostelle is the first and only all-women hoste...
20,Queen Elizabeth Chelsea,- 5.7km from city centre,7.5,(3687),Very Good,No Privates Available,"Dorms From\n₹1,681",Linen Included,PLEASE NOTE WE ONLY ACCEPT GUESTS FROM THE AGE...
21,Prime Backpackers Angel,- 3.6km from city centre,8.5,(871),Fabulous,No Privates Available,"Dorms From\n₹3,177",Linen Included,The hostel is housed in a historic building in...
22,Kabannas London St Pancras,- 3.3km from city centre,8.2,(2977),Fabulous,No Privates Available,"-20%\nDorms From\n₹3,806\n₹3,044",Linen Included,Kabannas London St Pancras has friendly recept...
23,London Backpackers,- 11.9km from city centre,8.1,(4568),Fabulous,No Privates Available,"Dorms From\n₹1,466",Linen Included,IMPORTANT NOTICE: \n\nThis hostel is for 18 - ...
24,Smart Camden Inn Hostel,- 4.4km from city centre,8.3,(3143),Fabulous,No Privates Available,"Dorms From\n₹2,174",Linen Included,"Located in the middle of Camden Town, we’re th..."
25,Astor Kensington,- 4.9km from city centre,8.6,(6595),Fabulous,"-10%\nPrivates From\n₹10,753\n₹9,678","-10%\nDorms From\n₹2,210\n₹1,989",Linen Included,Note: 18-40 yrs old only. Astor Kensington won...
26,St Christopher's Hammersmith,- 7.5km from city centre,7.7,(4389),Very Good,No Privates Available,"-10%\nDorms From\n₹1,926\n₹1,734",Linen Included,"The friendly, attentive, and welcoming staff o..."
27,Astor Victoria,- 1.8km from city centre,7.3,(15098),Very Good,"Privates From\n₹10,020","Dorms From\n₹1,746",Linen Included,Note: 18-40 yrs old only. Astor Victoria won 1...
28,Phoenix Hostel,- 4.2km from city centre,6.3,(4624),Good,No Privates Available,"-5%\nDorms From\n₹1,484\n₹1,410",Linen Included,"The Phoenix Bar & Hostel, housed in a homely E..."
29,Barmy Badger Backpackers,- 5.5km from city centre,9.1,(2041),Superb,"Privates From\n₹6,843",No Dorms Available,Free Breakfast,The Badger is unique for London in that we hav...